### ISSUE TITLE
How to add a theme to the html output? 

### ISSUE THREAD

**Issue by ghost** [man-group/PyBloqs#50]
Would be interesting to be able to add a customized theme to the HTML output (eg, bootstrap). Is that possible in this framework? Thank you!

**Comment by DominikMChrist** [comment]
Please have a look at pybloqs/static/css/pybloqs_default/main.css as a starting point. PyBloqs does not use a front-end framework like Bootstrap. If this is something of interest to you, happy to discuss the best way to implement it and to support any contribution to PyBloqs.
